name: release
on:
  workflow_dispatch:

jobs:          
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: install dependencies
        run: npm install --location=global appdmg

      - name: Create Release DMG
        run: sh create_release.sh

      - name: Get latest tag
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
        id: tag

      - name: package and upload
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.tag.outputs.version }}
          body: "ReaCoMa 2.0 .dmg installer"
          files: "*.dmg"
          prerelease: true
          tag_name: ${{ steps.tag.outputs.version }}
          draft: false
